### ISSUE TITLE
请问如何将知识图谱数据导入neo4j啊

### ISSUE THREAD

**Issue by 972461099** [liuhuanyong/QASystemOnMedicalKG#1]
我运行python build_medicalgraph.py并没有什么反应

**Comment by liuhuanyong** [comment]
您好，先配置neo4j地址，再分别执行cerate_nodes和create_rels两个函数。

**Comment by 972461099** [comment]
> 您好，先配置neo4j地址，再分别执行cerate_nodes和create_rels两个函数。

可以了，谢谢~

**Comment by backnero** [comment]
如何执行cerate_nodes和create_rels两个函数？是在neo4j中还是？

**Comment by jiaxinhong** [comment]
> > 您好，先配置neo4j地址，再分别执行cerate_nodes和create_rels两个函数。
> 
> 可以了，谢谢~

这两个函数是在build_medicalgraph.py文件中自己写两行代码调用呀，还是怎么弄，麻烦你了 #

**Comment by ttklm20** [comment]
handler = MedicalGraph()
handler.create_graphnodes()
handler.create_graphrels()

**Comment by liuhuanyong** [comment]
将知识图谱导入Neo4j数据库:
handler = MedicalGraph()
handler.create_graphnodes()
handler.create_graphrels()

**Comment by yeyuliang2015** [comment]
如何写成一个rest api接口供前端调用？

**Comment by swaker01** [comment]
你好，下面这种情况应该怎么办啊：UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 84: illegal multibyte sequence

**Comment by vonpower** [comment]
在open函数里加入参数: encoding="utf-8"

**Comment by vonpower** [comment]
> 你好，下面这种情况应该怎么办啊：UnicodeDecodeError: 'gbk' codec can't decode byte 0xaf in position 84: illegal multibyte sequence

在open函数里加入参数: encoding="utf-8"

**Comment by tectal** [comment]
> 如何写成一个rest api接口供前端调用？

@liuhuanyong

**Comment by tectal** [comment]
'''导出数据'''
    def export_data(self):
请问这个函数有什么作用呢？谢谢

**Comment by AladengodmanVicky** [comment]
> > 您好，先配置neo4j地址，再分别执行cerate_nodes和create_rels两个函数。
> 
> 可以了，谢谢~

请问您是如何执行create_nodes和create_rels这两个函数的呢,期待回复！！！

**Comment by AladengodmanVicky** [comment]
第三步启动问答：python chat_graph.py：
输入汉字
![image](https://user-images.githubusercontent.com/45462906/54325835-263e1e80-463f-11e9-8786-22919fcd63ce.png)
输入英文
![image](https://user-images.githubusercontent.com/45462906/54325861-4a016480-463f-11e9-8047-a94b9543fc4f.png)
请问@liuhuanyong刘老师这个问题怎么解决呢

**Comment by AladengodmanVicky** [comment]
> 第三步启动问答：python chat_graph.py：
> 输入汉字
> ![image](https://user-images.githubusercontent.com/45462906/54325835-263e1e80-463f-11e9-8786-22919fcd63ce.png)
> 输入英文
> ![image](https://user-images.githubusercontent.com/45462906/54325861-4a016480-463f-11e9-8047-a94b9543fc4f.png)
> 请问@liuhuanyong刘老师这个问题怎么解决呢

是因为没有安装某个依赖包吗

**Comment by tectal** [comment]
'''导出数据'''
def export_data(self):
请问这个函数有什么作用呢？谢谢 @liuhuanyong

**Comment by johnarchie1** [comment]
> 我运行python build_medicalgraph.py并没有什么反应

你好，想知道你最后问题具体怎么解决的，我也在调试这个代码，可以方便交流吗
