### ISSUE TITLE
disease.txt在dict文件夹下，first_name.txt未找到，但是原作者给出了数据，json格式的，在data文件夹下。所以不需要爬虫及相应的数据清洗工作，直接导入库使用就好。步骤：1.安装neo4j数据库，2.调用build_medicalgraph.py 3.调用question_parser.py，question_classifier.py，question_search.py，chatbot_graph.py

### ISSUE THREAD

**Issue by violahuyoujin** [liuhuanyong/QASystemOnMedicalKG#21]
disease.txt在dict文件夹下，first_name.txt未找到，但是原作者给出了数据，json格式的，在data文件夹下。所以不需要爬虫及相应的数据清洗工作，直接导入库使用就好。步骤：1.安装neo4j数据库，2.调用build_medicalgraph.py 3.调用question_parser.py，question_classifier.py，question_search.py，chatbot_graph.py

这其中根据提示需要安装相应的包， ahocorasick安装时需要安装visual studio。

_Originally posted by @chenxiangse in https://github.com/liuhuanyong/QASystemOnMedicalKG/issues/3#issuecomment-457186162_

**Comment by violahuyoujin** [comment]
你好，请问在如何调用build_medicalgraph.py？我在pycharm上运行该文件，但是没有成功向neo4j导入数据（配置已改）

**Comment by isolet** [comment]
已经导入json。但请问该json是如何生成的？

**Comment by Boat198** [comment]
请问解决了吗
