### ISSUE TITLE
UnicodeDecodeError: 'gbk' 

### ISSUE THREAD

**Issue by lsunsky** [liuhuanyong/QASystemOnMedicalKG#31]
Traceback (most recent call last):
  File "chatbot_graph.py", line 31, in <module>
    handler = ChatBotGraph()
  File "chatbot_graph.py", line 14, in __init__
    self.classifier = QuestionClassifier()
  File "C:\Users\13301\Desktop\QASystemOnMedicalKG-master\question_classifier.py", line 23, in __init__
    self.disease_wds= [i.strip() for i in open(self.disease_path) if i.strip()]
  File "C:\Users\13301\Desktop\QASystemOnMedicalKG-master\question_classifier.py", line 23, in <listcomp>
    self.disease_wds= [i.strip() for i in open(self.disease_path) if i.strip()]
UnicodeDecodeError: 'gbk' codec can't decode byte 0xa3 in position 29: illegal multibyte sequence

**Comment by littlepanda0716** [comment]
请问是怎么解决的呢？

**Comment by spiritwalking** [comment]
> Traceback (most recent call last): File "chatbot_graph.py", line 31, in handler = ChatBotGraph() File "chatbot_graph.py", line 14, in **init** self.classifier = QuestionClassifier() File "C:\Users\13301\Desktop\QASystemOnMedicalKG-master\question_classifier.py", line 23, in **init** self.disease_wds= [i.strip() for i in open(self.disease_path) if i.strip()] File "C:\Users\13301\Desktop\QASystemOnMedicalKG-master\question_classifier.py", line 23, in self.disease_wds= [i.strip() for i in open(self.disease_path) if i.strip()] UnicodeDecodeError: 'gbk' codec can't decode byte 0xa3 in position 29: illegal multibyte sequence

你好，请问你当时是如何解决的呢？

**Comment by mycfhs** [comment]
把build_medicalgraph.py   line 51 
for data in open(self.data_path):   改为  for data in open(self.data_path, encoding='utf-8'):
就能跑通了
